[tool.mypy]
files = "**/*.py"
exclude = [
    ".git",
    "__pycache__",
    ".ruff_cache",
    ".pytest_cache"
]


[[tool.mypy.overrides]]
module = [
    'fabric.*',
    'parameterized.*',
]
ignore_missing_imports = true
