name: Linters
inputs:
    command:
        required: true
        description: 'Running linter command'
runs:
    using: "composite"
    steps:
        # Must be run after the `setup_python_and_poetry` action.
        -   uses: actions/checkout@v4.1.1
        -   name: Install dependencies
            run: poetry install --with linter
            shell: bash
        -   name: Run Linter
            run: ${{ inputs.command }}
            shell: bash
