name: Linters
inputs:
    command:
        required: true
        description: 'Running linter command'
runs:
    using: "composite"
    steps:
        -   name: Set up Python
            uses: actions/setup-python@v5.1.0
            with:
                python-version: 3.12.6
        -   name: Install Poetry
            uses: snok/install-poetry@v1.3.4
            with:
                version: 1.5.0
                virtualenvs-create: false
        -   name: Install dependencies
            run: poetry install --with linter
            shell: bash
        -   name: Run Linter
            run: ${{ inputs.command }}
            shell: bash
