name: Publish Python Package

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    check-tag-from-main-branch:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v4.1.1
            -   name: Check if tag is on main branch
                run: |
                    if [[ $(git branch --contains ${{ github.ref }}) =~ "main" ]]; then
                        echo "Tag is on main branch"
                    else
                        echo "Tag is not on main branch"
                        exit 1
                    fi
    check-version-already-exist:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v4.1.1
            -   name: Check if version already exists
                run: |
                    PACKAGE_VERSION=$(poetry version -s)
                    STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" https://pypi.org/project/dddesign/$PACKAGE_VERSION/)
                    if [ "$STATUS_CODE" -eq 200 ]; then
                        echo "Version $PACKAGE_VERSION already exists"
                        exit 1
                    else
                        echo "Version $PACKAGE_VERSION doesn't exists"
                    fi
    build-and-publish-package:
        runs-on: ubuntu-20.04
        needs:
            - check-tag-from-main-branch
            - check-version-already-exist
        environment:
            name: pypi
            url: https://pypi.org/p/dddesign
        permissions:
            id-token: write
        steps:
            -   uses: actions/checkout@v4.1.1
            -   name: Set up Python
                uses: actions/setup-python@v5.1.0
                with:
                    python-version: 3.10.4
            -   name: Install Poetry
                uses: snok/install-poetry@v1.3.4
                with:
                    version: 1.5.0
            -   name: Build release distributions
                run: poetry build
            -   name: Publish release distributions
                uses: pypa/gh-action-pypi-publish@release/v1
