name: Publish Python Package

on:
    release:
        types: [ published ]

jobs:
    upload:
        runs-on: ubuntu-20.04
        steps:
          -   uses: actions/checkout@v4.1.1
          -   name: Set up Python
              uses: actions/setup-python@v5.1.0
              with:
                  python-version: 3.10.4
          -   name: Install Poetry
              uses: snok/install-poetry@v1.3.4
              with:
                  version: 1.5.0
          -   name: Deactivate poetry virtualenv
              run: poetry config virtualenvs.create false
          -   name: Build & Publish Python Package
              run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
