name: Publish Python Package

on:
    release:
        types: [ published ]

jobs:
    build-and-publish-packege:
        runs-on: ubuntu-20.04
        environment:
            name: pypi
            url: https://pypi.org/p/dddesign
        permissions:
            id-token: write
        steps:
            -   uses: actions/checkout@v4.1.1
            -   name: Set up Python
                uses: actions/setup-python@v5.1.0
                with:
                    python-version: 3.10.4
            -   name: Install Poetry
                uses: snok/install-poetry@v1.3.4
                with:
                    version: 1.5.0
            -   name: Build release distributions
                run: poetry build
            -   name: Publish release distributions
                uses: pypa/gh-action-pypi-publish@1.8.14
